### ISSUE TITLE
Progress tracking

### ISSUE THREAD

**Issue by barbatus** [barbatus/angular2-compiler#2]
- ~~Upgrade to Angular 2.4.3 and TypeScript 1.4~~
- ~~Test it with the What'sApp and Socially apps~~
- ~~Test it with the path mappings~~
- Work around  [issue](https://github.com/angular/angular/issues/11402) with the default exports 
- Initial unit tests
- Publish initial version that works in the default mode only (as a replacement of the current angular2-compiler)
- Add logging

**Comment by Zeioth** [comment]
Thank you for working on this!!

**Comment by joerex** [comment]
I noticed that we are now able to use the Angular CLI: https://blog.meteor.com/leverage-the-power-of-meteor-with-any-client-side-framework-bfb909141008.

It seems like this package will be necessary only if you don't want to use the Angular CLI. Is there any discussion in terms of the pros and cons of either direction?

**Comment by Zeioth** [comment]
Thank you @joerex ! Well the most obvious advantage of having native support in the compiler is that you don't need to manually rebuild every time you change a package.

Sadly this approach doesn't seems to work either. When I run:

    meteor create — example angular2-boilerplate myApp
    cd ./myApp
    bundle --source=./  --destination=./node_modules/client.bundle.js

I get this error during the process:

``` javascript
fs.js:641                                    
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
 
Error: ENOENT: no such file or directory, open '/home/zeioth/Escritorio/myApp/node_modules/client.bundle.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at Object.bundle (/usr/lib/node_modules/meteor-client-bundler/lib/bundler.js:92:6)
    at Command.<anonymous> (/usr/lib/node_modules/meteor-client-bundler/cli:37:13)
    at Command.listener (/usr/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:458:21)
```

**Comment by Zeioth** [comment]
Thank you so much @joerex. It worked!!

Well, as far as I understand, the point of implement this feature is that Meteor will recognize angular2 directly. So you won't need that tutorial in the future.

**EDIT:** Also, using the compiler, you can run the useful command

    meteor build

**Comment by joerex** [comment]
It's still unclear to me whether this package is usable or not right now. I'm trying to implement AOT compiling without moving to the angular cli. Is that currently possible? Thanks for you help on this.

**Comment by Urigo** [comment]
AOT compilation with the Meteor CLI just got merged on this [PR](https://github.com/Urigo/angular-meteor/pull/1654)
Will release a new version soon
